"""empty message

Revision ID: 004b26604e3c
Revises: 
Create Date: 2022-08-01 15:26:07.461296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004b26604e3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('buid', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bid')
    )
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('fuid', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fid')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.String(length=256), nullable=False),
    sa.Column('genrename', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genrename'),
    sa.UniqueConstraint('gid')
    )
    op.create_table('movielike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('mid', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlid')
    )
    op.create_table('movielist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('molid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('mid', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('molid')
    )
    op.create_table('moviereview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mrid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('mid', sa.String(length=256), nullable=False),
    sa.Column('review', sa.TEXT(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mrid')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.String(length=256), nullable=False),
    sa.Column('moviename', sa.String(length=256), nullable=False),
    sa.Column('coverimage', sa.String(length=256), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.Column('cast', sa.TEXT(), nullable=True),
    sa.Column('crew', sa.String(length=256), nullable=True),
    sa.Column('director', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('avg_rate', sa.FLOAT(), nullable=True),
    sa.Column('release_date', sa.String(length=256), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('mid', sa.String(length=256), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raid')
    )
    op.create_table('reviewlike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rlid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('mrid', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rlid')
    )
    op.create_table('userreview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('mrid', sa.String(length=256), nullable=False),
    sa.Column('review', sa.TEXT(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('verifycode', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('verifycode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('verifycode', sa.String(length=256), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('mid', sa.String(length=256), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vid')
    )
    op.create_table('wishWatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wid', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('mid', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishWatch')
    op.drop_table('viewHistory')
    op.drop_table('verifycode')
    op.drop_table('users')
    op.drop_table('userreview')
    op.drop_table('reviewlike')
    op.drop_table('rating')
    op.drop_table('movies')
    op.drop_table('moviereview')
    op.drop_table('movielist')
    op.drop_table('movielike')
    op.drop_table('genre')
    op.drop_table('follow')
    op.drop_table('blockList')
    # ### end Alembic commands ###
