"""empty message

Revision ID: 2626dfb05757
Revises: dcb8bbd0500e
Create Date: 2022-06-23 21:47:45.666653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2626dfb05757'
down_revision = 'dcb8bbd0500e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.String(length=256), nullable=False),
    sa.Column('genrename', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genrename'),
    sa.UniqueConstraint('gid')
    )
    op.drop_column('movies', 'Off_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('Off_data', mysql.DATETIME(), nullable=True))
    op.drop_table('genre')
    # ### end Alembic commands ###
