"""empty message

Revision ID: 6dd406922bd9
Revises: 307567df618f
Create Date: 2022-06-24 17:43:39.797271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd406922bd9'
down_revision = '307567df618f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'year')
    # ### end Alembic commands ###
