"""empty message

Revision ID: 84fdb7110818
Revises: a7bdc80f7225
Create Date: 2022-07-15 14:51:10.975336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84fdb7110818'
down_revision = 'a7bdc80f7225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewlike', sa.Column('mrid', sa.String(length=256), nullable=False))
    op.drop_column('reviewlike', 'urid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewlike', sa.Column('urid', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('reviewlike', 'mrid')
    # ### end Alembic commands ###
