"""empty message

Revision ID: 99283741cbaf
Revises: 
Create Date: 2022-07-21 00:38:56.194590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99283741cbaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifycode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('verifycode', sa.String(length=256), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reviewlike', sa.Column('mrid', sa.String(length=256), nullable=False))
    op.drop_column('reviewlike', 'urid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewlike', sa.Column('urid', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('reviewlike', 'mrid')
    op.drop_table('verifycode')
    # ### end Alembic commands ###
