"""rating table and movies table add duration

Revision ID: dcb8bbd0500e
Revises: a037b7cfdfd0
Create Date: 2022-06-22 13:12:39.661162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcb8bbd0500e'
down_revision = 'a037b7cfdfd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('mid', sa.String(length=256), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raid')
    )
    op.drop_index('genrename', table_name='genre')
    op.drop_index('gid', table_name='genre')
    op.drop_table('genre')
    op.drop_column('moviereview', 'rate')
    op.add_column('movies', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'duration')
    op.add_column('moviereview', sa.Column('rate', mysql.FLOAT(), nullable=True))
    op.create_table('genre',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gid', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('genrename', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('active', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ctime', mysql.DATETIME(), nullable=False),
    sa.Column('utime', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('gid', 'genre', ['gid'], unique=True)
    op.create_index('genrename', 'genre', ['genrename'], unique=True)
    op.drop_table('rating')
    # ### end Alembic commands ###
