"""empty message

Revision ID: ead4b39f20f0
Revises: 
Create Date: 2022-07-15 21:43:18.094881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ead4b39f20f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewlike', sa.Column('mrid', sa.String(length=256), nullable=False))
    op.drop_column('reviewlike', 'urid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewlike', sa.Column('urid', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('reviewlike', 'mrid')
    # ### end Alembic commands ###
